Exception in thread "main" java.lang.NullPointerException
	at java_proj_group_15.Main.run(Unknown Source)
	at java_proj_group_15.Main.main(Unknown Source)
